import {test} from 'node:test';import assert from 'node:assert/strict';import {initial,register,claim,lines,personal,snapshot,adminAction,csv,normalize,upgrade,addNote,roundDue,advanceRound} from '../lib/game.mjs';
function player(s,n){return register(s,{name:'Player '+n,company:'Company',type:'email',contact:`p${n}@example.com`,consent:true});}
function tap(s,p,i){return claim(s,p.token,{board:s.board.id,index:i,request:crypto.randomUUID()});}
test('all twelve lines and one kit for multi-line tap',()=>{for(let line of lines){let s=initial();s.settings.firstFive=0;let ps=line.map((_,i)=>player(s,i));line.forEach((n,i)=>tap(s,ps[i],n));assert.equal(s.claims.at(-1).lines.length,1);assert.equal(s.kits.length,1);}let s=initial();s.settings.firstFive=0;[1,2,3,4,5,10,15,20].forEach((n,i)=>tap(s,player(s,i),n));tap(s,player(s,9),0);assert.equal(s.claims.at(-1).lines.length,2);assert.equal(s.kits.length,1);});
test('legacy first-five awards and retry remain valid',()=>{let s=initial();s.settings.firstFive=5;s.settings.cooldown=10;for(let i=0;i<6;i++)tap(s,player(s,i),i);assert.equal(s.kits.filter(k=>k.reason==='first_five').length,5);let p=s.players[0],c=s.claims[0];assert.throws(()=>tap(s,p,6),/not ready/);claim(s,p.token,{board:c.board,index:c.index,request:c.request});assert.equal(s.claims.length,6);assert.equal(personal(s,p.token).kits.length,1);});
test('cap, reset, no repeated set and one line kit per player over 4 boards',()=>{let s=initial();s.settings.cooldown=0;let ps=Array.from({length:60},(_,i)=>player(s,i));let previous=s.board.set;for(let round=0;round<4;round++){for(let i=0;i<25;i++)tap(s,ps[(round*25+i)%60],i);assert.notEqual(s.board.set,previous);previous=s.board.set;assert.ok(s.kits.length<=5+3*(round+1));}assert.equal(s.claims.length,100);assert.equal(s.history.length,4);for(let p of ps)assert.ok(s.kits.filter(k=>k.player===p.id&&k.reason==='line_win').length<=1);});
test('undo current claims revokes uncollected kits and preserves audit',()=>{let s=initial();s.settings.firstFive=5;let p=player(s,0);let c=tap(s,p,0);adminAction(s,{action:'undo',id:c.id});assert.equal(s.board.squares[0].claim,null);assert.equal(personal(s,p.token).kits.length,0);assert.ok(c.undone);let d=tap(s,p,1),kit=s.kits.find(k=>k.claim===d.id);adminAction(s,{action:'hand',code:kit.code});assert.throws(()=>adminAction(s,{action:'undo',id:d.id}),/already been handed/);});
test('public state never exposes identity, tags, ratings or prizes',()=>{let s=initial();tap(s,player(s,0),0);let out=JSON.stringify(snapshot(s));for(let v of ['Player 0','p0@example.com'])assert.ok(!out.includes(v),v);const forbidden=new Set(['token','wedge','persona','first_five','code','rating']);function check(value){if(!value||typeof value!=='object')return;for(const [key,child] of Object.entries(value)){assert.ok(!forbidden.has(key),key);check(child);}}check(JSON.parse(out));});
test('contact normalization, duplicate protection, CSV safety',()=>{assert.equal(normalize('linkedin','www.linkedin.com/in/Jim/'),'https://linkedin.com/in/jim');assert.throws(()=>normalize('linkedin','https://linkedin.com.evil.test/in/jim'));let s=initial(),p=player(s,1);assert.throws(()=>player(s,1),/already registered/);p.name='=HYPERLINK("x")';tap(s,p,0);assert.ok(csv(s).startsWith('\uFEFF'));assert.ok(csv(s).includes("'=HYPERLINK"));});
test('stale board, paused and ended claims are rejected',()=>{let s=initial(),p=player(s,1);s.settings.paused=true;assert.throws(()=>tap(s,p,0),/paused/);s.settings.paused=false;s.settings.ended=true;assert.throws(()=>tap(s,p,0),/ended/);s.settings.ended=false;assert.throws(()=>claim(s,p.token,{board:'old',index:0,request:'new'}),/new board/);});

test('shared game allows three immediate picks, no signup prize, and resets picks next round',()=>{let s=initial(),p=player(s,100);tap(s,p,0);tap(s,p,1);tap(s,p,2);assert.equal(personal(s,p.token).picksLeft,0);assert.equal(s.kits.length,0);assert.throws(()=>tap(s,p,3),/used your picks/);adminAction(s,{action:'skip'});assert.equal(personal(s,p.token).picksLeft,3);tap(s,p,3);assert.equal(personal(s,p.token).picksLeft,2);});
test('personal cards are independent and award only one line kit per person',()=>{let s=initial('personal'),a=player(s,200),b=player(s,201);let aBoard=s.personalBoards[a.id],bBoard=s.personalBoards[b.id];assert.notEqual(aBoard.id,bBoard.id);for(let i=0;i<5;i++)claim(s,a.token,{board:aBoard.id,index:i,request:crypto.randomUUID()});assert.equal(snapshot(s,b.token).board.count,0);assert.equal(snapshot(s,a.token).board.count,5);assert.equal(personal(s,a.token).kits.length,1);for(let i=5;i<25;i++)claim(s,a.token,{board:aBoard.id,index:i,request:crypto.randomUUID()});assert.equal(personal(s,a.token).kits.length,1);assert.equal(snapshot(s,a.token).board.no,2);assert.equal(personal(s,a.token).picksLeft,25);assert.equal(snapshot(s,b.token).board.no,1);assert.equal(s.board.no,1);});
test('written notes are private until approved and never publish author details',()=>{let s=initial(),p=player(s,300);let input={text:'We paste the same report into five tools.',request:crypto.randomUUID()};let n=addNote(s,p.token,input);addNote(s,p.token,input);assert.equal(s.notes.length,1);assert.equal(snapshot(s).callouts.length,0);assert.ok(csv(s).includes(input.text));adminAction(s,{action:'moderate',id:n.id,status:'approved'});assert.deepEqual(snapshot(s).callouts,[{id:n.id,text:n.text}]);assert.ok(!JSON.stringify(snapshot(s)).includes(p.name));adminAction(s,{action:'moderate',id:n.id,status:'hidden'});assert.equal(snapshot(s).callouts.length,0);assert.throws(()=>addNote(s,p.token,{text:'short',request:'x'}),/8 to 180/);});
test('upgrade preserves historical claims and prizes while refreshing open squares',()=>{let s=initial();s.ruleVersion=1;s.settings.cooldown=10;s.settings.firstFive=5;let p=player(s,400);let c=tap(s,p,0);let oldPain=structuredClone(c.pain),code=s.kits[0].code;s.board.squares[1].short='OLD';s.board.squares[1].revision=1;upgrade(s);assert.equal(s.settings.picksPerRound,3);assert.equal(s.settings.cooldown,0);assert.equal(s.settings.firstFive,0);assert.notEqual(s.board.squares[1].short,'OLD');assert.deepEqual(c.pain,oldPain);assert.equal(s.kits[0].code,code);});

test('scheduled rounds pause play, restore picks, and preserve wins and notes',()=>{for(const variant of ['shared','personal']){const s=initial(variant),a=player(s,500),b=player(s,501);const current=()=>variant==='personal'?s.personalBoards[a.id]:s.board;s.settings.picksPerRound=10;for(let i=0;i<5;i++)claim(s,a.token,{board:current().id,index:i,request:crypto.randomUUID()});const kit=personal(s,a.token).kits[0].code;const old=current().id,other=variant==='personal'?s.personalBoards[b.id].id:null;addNote(s,a.token,{text:'We forget to email people we meet at events.',request:crypto.randomUUID()});const start=Date.now()+60000;adminAction(s,{action:'announce',startAt:start,message:'Panel break. Next round soon.'});assert.equal(s.settings.paused,true);assert.equal(!!roundDue(s,start-1),false);assert.equal(!!roundDue(s,start),true);assert.throws(()=>claim(s,a.token,{board:old,index:6,request:crypto.randomUUID()}),/paused/);advanceRound(s,start);assert.equal(!!roundDue(s,start),false);assert.notEqual(current().id,old);if(other)assert.notEqual(s.personalBoards[b.id].id,other);assert.equal(s.settings.paused,false);assert.equal(personal(s,a.token).picksLeft,variant==='personal'?25:10);assert.equal(personal(s,a.token).kits[0].code,kit);assert.equal(personal(s,a.token).wins[0].kit,kit);assert.equal(personal(s,a.token).notes.length,1);}});
test('ending or cancelling a scheduled round prevents an automatic start',()=>{const s=initial();adminAction(s,{action:'announce',startAt:Date.now()+60000});adminAction(s,{action:'cancel_announcement'});assert.equal(!!roundDue(s,Date.now()+120000),false);assert.equal(s.settings.paused,true);adminAction(s,{action:'announce',startAt:Date.now()+60000});adminAction(s,{action:'end'});assert.equal(!!roundDue(s,Date.now()+120000),false);assert.equal(s.settings.ended,true);});
