import {test} from 'node:test';
import assert from 'node:assert/strict';
import {personas,personaPains} from '../lib/personas.mjs';
import {initialRoom,ROUND_MS,CALL_MS,joinRoom,selectRoomRole,selectRoomPath,advanceRoom,calledFor,matchCall,submitProblems,roomSnapshot,roomAdmin,roomAdminAction,roomDue,tickRoom,roomCsv,roomNote} from '../lib/hosted-game.mjs';
const T=1900000000000;
function join(s,id,path='bingo',role='sales',at=T){const p=joinRoom(s,{name:'Demo '+id,company:'Example',type:'email',contact:`test-${id}@example.com`,consent:true,path},undefined,at);if(role)selectRoomRole(s,p.token,role,at);return p;}
function match(s,p,pain,at){return matchCall(s,p.token,{round:s.round.id,pain,request:crypto.randomUUID()},at);}
function win(s,p){const calls=s.round.calls.map((c,i)=>({...c,at:s.round.startedAt+i*CALL_MS})).filter(c=>c.role===p.role);for(const c of calls)match(s,p,c.pain.id,c.at);return calls;}
function direct(s,p){return submitProblems(s,p.token,{pains:personaPains(p.role).slice(0,3).map(p=>p.id),request:crypto.randomUUID()},T+500);}
test('details are saved before role; direct path does not start caller',()=>{const s=initialRoom(),p=join(s,1,'direct',null);assert.equal(p.role,null);assert.equal(s.round,null);selectRoomRole(s,p.token,'risk',T);assert.equal(s.round,null);assert.equal(roomSnapshot(s,p.token,T).me.role,'risk');assert.ok(roomCsv(s).includes('registration'));});
test('every role gets exactly six unique tiles and three matching calls before three minutes',()=>{let cases=0;for(let iteration=0;iteration<40;iteration++){const s=initialRoom();const players=personas.map((r,i)=>join(s,iteration*100+i,'bingo',r.id));for(const p of players){const card=s.round.cards[p.role],calls=s.round.calls.filter(c=>c.role===p.role);assert.equal(card.length,6);assert.equal(new Set(card.map(p=>p.id)).size,6);assert.equal(calls.length,3);assert.ok(calls.every(c=>card.some(p=>p.id===c.pain.id)));win(s,p);const me=roomSnapshot(s,p.token,s.round.startedAt+ROUND_MS-1).me;assert.equal(me.matches,3);assert.equal(me.wins.length,1);assert.ok(me.kit);cases++;}assert.equal(s.kits.length,8);assert.ok(s.wins.every(w=>w.at<s.round.startedAt+ROUND_MS));}assert.equal(cases,320);});
test('uncalled, wrong-persona and anonymous matches cannot win',()=>{const s=initialRoom(),p=join(s,2);const c=s.round.calls.find(c=>c.role===p.role);assert.throws(()=>match(s,p,c.pain.id,s.round.startedAt-1),/not been called/);const other=s.round.calls.find(c=>!s.round.cards[p.role].some(p=>p.id===c.pain.id));assert.throws(()=>match(s,p,other.pain.id,T+180000),/on your card/);assert.throws(()=>matchCall(s,'bad',{round:s.round.id,pain:c.pain.id,request:'test-request'},T),/join the room/);});
test('safe retry and duplicate taps create exactly one match and one kit',()=>{const s=initialRoom(),p=join(s,3);const calls=s.round.calls.map((c,i)=>({...c,at:s.round.startedAt+i*CALL_MS})).filter(c=>c.role===p.role);for(const c of calls){const req={round:s.round.id,pain:c.pain.id,request:crypto.randomUUID()};matchCall(s,p.token,req,c.at);matchCall(s,p.token,req,c.at+1);}assert.equal(s.matches.length,3);assert.equal(s.wins.length,1);assert.equal(s.kits.length,1);assert.throws(()=>match(s,p,calls[0].pain.id,T+180000),/already matched/);});
test('direct path validates three unique role problems and persists a single submission',()=>{const s=initialRoom(),p=join(s,4,'direct');const ids=personaPains(p.role).slice(0,3).map(p=>p.id);for(const pains of [[ids[0]], [ids[0],ids[0],ids[1]],['r-01','r-02','r-03']])assert.throws(()=>submitProblems(s,p.token,{pains,request:crypto.randomUUID()},T));const entry=direct(s,p);direct(s,p);assert.equal(s.experiences.length,1);assert.equal(s.kits.length,1);assert.deepEqual(roomSnapshot(s,p.token,T).me.completed.pains.map(p=>p.id),ids);assert.equal(entry.reward.status,'earned');});
test('both path orders and repeated rounds preserve a single prize',()=>{for(const first of ['bingo','direct']){const s=initialRoom(),p=join(s,first,first);if(first==='direct')direct(s,p);else win(s,p);const code=s.kits[0].code;selectRoomPath(s,p.token,first==='direct'?'bingo':'direct',T+1000);if(first==='direct')win(s,p);else direct(s,p);selectRoomPath(s,p.token,'bingo',T+1000);advanceRoom(s,T+ROUND_MS);win(s,p);assert.equal(s.kits.length,1);assert.equal(s.kits[0].code,code);assert.equal(s.experiences.length,1);assert.equal(s.wins.length,2);}});
test('late arrivals can match earlier calls; new rounds clear only current matches',()=>{const s=initialRoom();join(s,10);const p=join(s,11,'bingo','support',s.round.startedAt+150000);const end=s.round.startedAt+ROUND_MS-1;for(const c of s.round.calls.filter(c=>c.role===p.role))match(s,p,c.pain.id,end);assert.equal(roomSnapshot(s,p.token,end).me.matches,3);const code=s.kits[0].code,old=s.round.id;assert.equal(roomDue(s,end),false);tickRoom(s,end+1);assert.notEqual(s.round.id,old);assert.equal(roomSnapshot(s,p.token,end+1).me.matches,0);assert.equal(roomSnapshot(s,p.token,end+1).me.kit.code,code);assert.throws(()=>matchCall(s,p.token,{round:old,pain:'x',request:'old-round-test'},end+1),/fresh round/);});
test('panel pause freezes calls and resumes their remaining time; direct path stays open',()=>{const s=initialRoom(),p=join(s,12);const pause=s.round.startedAt+30000,before=calledFor(s,pause).length;roomAdminAction(s,{action:'pause'},pause);assert.equal(calledFor(s,pause+600000).length,before);assert.equal(!!roomDue(s,pause+600000),false);assert.throws(()=>match(s,p,s.round.cards[p.role][0].id,pause+1),/paused/);const d=join(s,13,'direct','risk',pause+1);direct(s,d);assert.equal(s.experiences.length,1);roomAdminAction(s,{action:'pause'},pause+600000);assert.equal(calledFor(s,pause+600000).length,before);});
test('scheduled restart and event ending preserve prizes and suppress inappropriate writes',()=>{const s=initialRoom(),p=join(s,14);win(s,p);const code=s.kits[0].code;roomAdminAction(s,{action:'announce',startAt:T+300000,message:'Panel'},T+1000);assert.ok(roomDue(s,T+300000));tickRoom(s,T+300000);const id=s.round.id;tickRoom(s,T+300000);assert.equal(s.round.id,id);assert.equal(s.settings.paused,false);roomAdminAction(s,{action:'end'},T+301000);assert.equal(!!roomDue(s,T+999999),false);assert.throws(()=>direct(s,p),/ended/);assert.equal(roomSnapshot(s,p.token,T+301000).me.kit.code,code);roomAdminAction(s,{action:'hand',code},T+301000);assert.equal(s.kits[0].handed,T+301000);roomAdminAction(s,{action:'hand',code},T+302000);assert.equal(s.kits[0].handed,T+301000);});
test('one stock pool covers both paths and cannot exceed inventory',()=>{const s=initialRoom();s.settings.kitLimit=1;const a=join(s,15,'direct'),b=join(s,16);direct(s,a);win(s,b);assert.equal(s.kits.length,1);assert.equal(s.wins[0].reward.status,'out-of-stock');assert.equal(roomSnapshot(s,b.token,T).me.kit,null);assert.equal(roomSnapshot(s).stockAvailable,false);});
test('reported pains, participation, registrants and notes stay distinguishable and private',()=>{const s=initialRoom(),a=join(s,17),b=join(s,18,'direct');win(s,a);direct(s,b);roomNote(s,a.token,{text:'A note about a repetitive report.',request:'note-request'},T);const publicData=roomSnapshot(s,undefined,T);assert.equal(publicData.me,null);assert.equal(publicData.callouts.length,0);for(const value of [a.name,a.contact,a.token,b.contact,s.kits[0].code])assert.ok(!JSON.stringify(publicData).includes(value));const admin=roomAdmin(s,T);assert.equal(admin.attendees.find(p=>p.id===a.id).reported.length,0);assert.equal(admin.attendees.find(p=>p.id===b.id).reported.length,3);roomAdminAction(s,{action:'moderate',id:s.notes[0].id,status:'approved'},T);assert.equal(roomSnapshot(s).callouts.length,1);a.name='=HYPERLINK("bad")';const out=roomCsv(s);assert.ok(out.includes("'=HYPERLINK"));assert.ok(out.includes('bingo match — not a reported problem'));assert.ok(out.includes('reported problem'));assert.ok(out.includes('registration'));});
test('contact reuse cannot steal a saved card and card state survives serialization',()=>{const s=initialRoom(),p=join(s,19);const saved=JSON.parse(JSON.stringify(s));assert.equal(roomSnapshot(saved,p.token,T).me.name,p.name);assert.throws(()=>join(s,19),/already joined/);assert.equal(roomSnapshot(saved,'other',T).me,null);});
test('first Bingo entrant cannot override a scheduled panel break',()=>{const s=initialRoom();roomAdminAction(s,{action:'announce',startAt:T+60000,message:'Panel in progress'},T);const p=join(s,20,'bingo','risk',T+5000);assert.equal(s.round,null);assert.equal(s.settings.paused,true);assert.equal(s.settings.nextRoundAt,T+60000);selectRoomPath(s,p.token,'direct',T+10000);selectRoomPath(s,p.token,'bingo',T+11000);assert.equal(s.round,null);assert.equal(s.settings.paused,true);tickRoom(s,T+60000);assert.ok(s.round);assert.equal(s.settings.paused,false);});
