import assert from 'node:assert/strict';
const base='http://127.0.0.1:5173',stamp=Date.now();
async function post(mode,p,cookie=''){let r=await fetch(base+'/api/game?mode='+mode,{method:'POST',headers:{origin:base,'content-type':'application/json',cookie},body:JSON.stringify(p)});let body=await r.json();return {status:r.status,body,cookie:r.headers.get('set-cookie')?.split(';')[0]||cookie};}
const get=async(mode,cookie='',suffix='')=>(await fetch(base+'/api/game?mode='+mode+suffix,{headers:{cookie}})).json();
let admin=await post('practice',{action:'login',pin:process.env.ADMIN_PIN});assert.equal(admin.status,200);let baseline=await get('practice',admin.cookie,'&admin=1');await post('practice',{action:'skip'},admin.cookie);await post('practice',{action:'settings',picksPerRound:3,cap:3},admin.cookie);
const register=async(mode,i)=>{let p=await post(mode,{action:'register',name:'V2 Test '+i,company:'Example Co',type:'email',contact:`v2-${stamp}-${i}@example.com`,consent:true});assert.equal(p.status,200,JSON.stringify(p.body));return p;};
let ps=[];for(let i=0;i<60;i++)ps.push(await register('practice',i));let b=ps[0].body.board;let race=await Promise.all(ps.slice(0,20).map(p=>post('practice',{action:'claim',board:b.id,index:0,request:crypto.randomUUID()},p.cookie)));assert.equal(race.filter(r=>r.status===200).length,1);assert.equal(race.filter(r=>r.status===409).length,19);
for(let round=0;round<4;round++){let snap=await get('practice');for(let i=0;i<25;i++){if(snap.board.squares[i].claimed)continue;let r=await post('practice',{action:'claim',board:snap.board.id,index:i,request:crypto.randomUUID()},ps[(round*25+i)%60].cookie);assert.equal(r.status,200,JSON.stringify(r.body));}}
let end=await get('practice',admin.cookie,'&admin=1');assert.ok(end.kits.length-baseline.kits.length<=12);let quota=await register('practice','quota'),qb=quota.body.board;for(let i=0;i<3;i++)assert.equal((await post('practice',{action:'claim',board:qb.id,index:i,request:crypto.randomUUID()},quota.cookie)).status,200);assert.equal((await post('practice',{action:'claim',board:qb.id,index:3,request:crypto.randomUUID()},quota.cookie)).status,429);
let note=await post('practice',{action:'note',text:'We paste the same update into three tools.',request:crypto.randomUUID()},quota.cookie);assert.equal(note.status,200);let n=note.body.me.notes.at(-1);assert.ok(!(await get('practice')).callouts.some(c=>c.id===n.id));await post('practice',{action:'moderate',id:n.id,status:'approved'},admin.cookie);let pub=await get('practice');assert.ok(pub.callouts.some(c=>c.id===n.id));assert.ok(!JSON.stringify(pub).includes('V2 Test'));
let a=await register('personal','soloA'),c=await register('personal','soloB');assert.notEqual(a.body.board.id,c.body.board.id);for(let i=0;i<5;i++){let result=await post('personal',{action:'claim',board:a.body.board.id,index:i,request:crypto.randomUUID()},a.cookie);assert.equal(result.status,200,JSON.stringify(result.body));if(i===4)assert.equal(result.body.me.kits.length,1);}assert.equal((await get('personal',c.cookie)).board.count,0);assert.equal((await get('personal',a.cookie)).board.count,5);assert.equal((await fetch(base+'/api/game?mode=practice&admin=1')).status,401);console.log('PASS: 20-way collision, 60-player/four-round run, 3-pick limit, private notes/approval, isolated personal cards, line prize, admin privacy.');

// A due round is advanced once even when many clients poll simultaneously.
await post('practice',{action:'announce',startAt:Date.now()+1500,message:'Test break'},admin.cookie);let before=(await get('practice')).board.id;await new Promise(r=>setTimeout(r,1600));const polled=await Promise.all(Array.from({length:20},()=>get('practice')));assert.equal(new Set(polled.map(x=>x.board.id)).size,1);assert.notEqual(polled[0].board.id,before);assert.equal(polled[0].settings.nextRoundAt,null);assert.equal(polled[0].settings.paused,false);console.log('PASS: concurrent polling advances a scheduled round exactly once.');
