import { env } from 'cloudflare:workers';
import {fail} from '../../../lib/game.mjs';
import {initialRoom,roomDue,tickRoom,joinRoom,selectRoomRole,selectRoomPath,matchCall,submitProblems,roomNote,roomSnapshot,roomAdmin,roomAdminAction,roomCsv} from '../../../lib/hosted-game.mjs';
const E=()=>env as any;
const enc=new TextEncoder();
const cookie=(r:Request,k:string)=>r.headers.get('cookie')?.split('; ').find(v=>v.startsWith(k+'='))?.slice(k.length+1)||'';
const json=(x:any,status=200,headers:any={})=>Response.json(x,{status,headers:{'Cache-Control':'no-store',...headers}});
async function key(){if(!E().ADMIN_SECRET)fail('Admin access is not configured.',503);return crypto.subtle.importKey('raw',enc.encode(E().ADMIN_SECRET),{name:'HMAC',hash:'SHA-256'},false,['sign','verify']);}
const hex=(b:ArrayBuffer)=>Array.from(new Uint8Array(b),v=>v.toString(16).padStart(2,'0')).join('');
async function isAdmin(r:Request){let val=cookie(r,'cotera_admin');let [exp,sig]=val.split('.');if(!exp||Number(exp)<Date.now()||!sig||!/^[a-f0-9]{64}$/.test(sig))return false;return crypto.subtle.verify('HMAC',await key(),new Uint8Array(sig.match(/../g)!.map(v=>parseInt(v,16))),enc.encode(exp));}
async function rate(r:Request,kind:string,max:number){const bucket=Math.floor(Date.now()/60000);let ip=r.headers.get('cf-connecting-ip')||'local';let id=kind+':'+ip+':'+bucket;let row=await E().DB.prepare('INSERT INTO attempts(id,count,expires) VALUES (?,1,?) ON CONFLICT(id) DO UPDATE SET count=count+1 RETURNING count').bind(id,Date.now()+120000).first();if(row.count>max)fail('Too many attempts. Please wait a minute.',429);if(Math.random()<0.01)await E().DB.prepare('DELETE FROM attempts WHERE expires < ?').bind(Date.now()).run();}
function sessionCookie(r:Request,k:string,v:string){return `${k}=${v}; HttpOnly; SameSite=Strict; Path=/; Max-Age=604800${new URL(r.url).protocol==='https:'?'; Secure':''}`;}
function context(r:Request){const u=new URL(r.url),mode=['personal','practice'].includes(u.searchParams.get('mode')||'')?'personal':'event';return {u,mode,token:cookie(r,'cotera_hosted_'+mode)};}
async function read(mode:string){const id='hosted:'+mode;const db=E().DB;let row=await db.prepare('SELECT version,data FROM games WHERE id = ?').bind(id).first();if(!row){await db.prepare('INSERT OR IGNORE INTO games(id,version,data) VALUES (?,0,?)').bind(id,JSON.stringify(initialRoom())).run();row=await db.prepare('SELECT version,data FROM games WHERE id = ?').bind(id).first();}return {version:row.version,state:JSON.parse(row.data)};}
async function mutate(mode:string,fn:(s:any)=>any){for(let i=0;i<30;i++){const {version,state}=await read(mode);tickRoom(state);const result=fn(state);state.version=version+1;const changed=await E().DB.prepare('UPDATE games SET data = ?, version = ? WHERE id = ? AND version = ?').bind(JSON.stringify(state),state.version,'hosted:'+mode,version).run();if(changed.meta.changes===1)return {state,result};await new Promise(r=>setTimeout(r,10+Math.random()*35));}fail('The booth is busy. Please retry.',503);throw new Error();}
const view=(state:any,mode:string,token?:string)=>({...roomSnapshot(state,token),scope:mode});
export async function GET(r:Request){try{const {u,mode,token}=context(r),admin=u.searchParams.has('admin'),exporting=u.searchParams.has('export');if((admin||exporting)&&!await isAdmin(r))return json({error:'Enter the booth PIN.'},401);let {state}=await read(mode);if(roomDue(state))state=(await mutate(mode,()=>null)).state;if(exporting)return new Response(roomCsv(state),{headers:{'Content-Type':'text/csv; charset=utf-8','Content-Disposition':`attachment; filename="cotera-${mode}-${new Date().toISOString().slice(0,10)}.csv"`,'Cache-Control':'no-store'}});return json(admin?{...roomAdmin(state),scope:mode}:view(state,mode,u.searchParams.has('public')?undefined:token));}catch(e:any){console.error('Room read failed',e.message);return json({error:e.status?e.message:'Connection interrupted. Retrying…'},e.status||503);}}
export async function POST(r:Request){try{
 if(r.headers.get('origin')!==new URL(r.url).origin)fail('Please reload this page.',403);const raw=await r.text();if(raw.length>8192)fail('Request too large.',413);let input:any;try{input=JSON.parse(raw);}catch{fail('Invalid request.');}if(!input||typeof input!=='object')fail('Invalid request.');
 const {mode,token}=context(r);
 if(input.action==='login'){await rate(r,'login',12);if(!E().ADMIN_PIN)fail('Admin access is not configured.',503);const a=await crypto.subtle.digest('SHA-256',enc.encode(String(input.pin||''))),b=await crypto.subtle.digest('SHA-256',enc.encode(E().ADMIN_PIN));let diff=0;new Uint8Array(a).forEach((v,i)=>diff|=v^new Uint8Array(b)[i]);if(diff)fail('Incorrect PIN.',401);const exp=String(Date.now()+12*3600000),sig=hex(await crypto.subtle.sign('HMAC',await key(),enc.encode(exp)));return json({ok:true},200,{'Set-Cookie':sessionCookie(r,'cotera_admin',exp+'.'+sig)});}
 if(input.action==='restart_practice'){if(mode!=='personal')fail('Only available in practice.',403);return json({ok:true},200,{'Set-Cookie':sessionCookie(r,'cotera_hosted_'+mode,'').replace('Max-Age=604800','Max-Age=0')});}
 if(input.action==='register'){await rate(r,'room-register',400);const {state,result}=await mutate(mode,s=>joinRoom(s,input,token));return json(view(state,mode,result.token),200,{'Set-Cookie':sessionCookie(r,'cotera_hosted_'+mode,result.token)});}
 const actions:any={role:selectRoomRole,path:selectRoomPath,match:matchCall,problems:submitProblems,note:roomNote};
 if(Object.hasOwn(actions,input.action)){await rate(r,'room-write',2400);const {state}=await mutate(mode,s=>actions[input.action](s,token,input.action==='role'?input.role:input.action==='path'?input.path:input));return json(view(state,mode,token));}
 if(!await isAdmin(r))fail('Enter the booth PIN.',401);if(input.action==='next_call'&&mode!=='personal')fail('Speed controls are only available in practice.',403);const {state}=await mutate(mode,s=>roomAdminAction(s,input));return json({...roomAdmin(state),scope:mode});
 }catch(e:any){console.error('Room action failed',e.message);return json({error:e.status?e.message:'Could not save. Please try again.'},e.status||503);}}
