import sets from '../pain-points.json' with {type:'json'};
import {getPersona,personaPains,painCatalog,sharedAIIds} from './personas.mjs';
export const lines=[...Array.from({length:5},(_,r)=>Array.from({length:5},(_,c)=>r*5+c)),...Array.from({length:5},(_,c)=>Array.from({length:5},(_,r)=>r*5+c)),[0,6,12,18,24],[4,8,12,16,20]];
export const lineNames=['Row 1','Row 2','Row 3','Row 4','Row 5','B column','I column','N column','G column','O column','Diagonal 1','Diagonal 2'];
const uid=()=>crypto.randomUUID();
const currentCopy=new Map(painCatalog.map(p=>[p.id,p]));
const currentShort=pain=>currentCopy.get(pain.id)?.short||pain.short;
export function board(no=1,previous=-1,role=null){
 let choices=sets.map((_,i)=>i).filter(i=>i!==previous);
 let set=role?-1:choices[Math.floor(Math.random()*choices.length)];
 let squares=structuredClone(role?personaPains(role):sets[set]);
 if(squares.length<25)fail('This role does not have enough problems for a card.');
 for(let i=squares.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[squares[i],squares[j]]=[squares[j],squares[i]];}
 if(role){const core=squares.filter(p=>!sharedAIIds.includes(p.id)).slice(0,22),ai=squares.filter(p=>sharedAIIds.includes(p.id)).slice(0,3);if(core.length<22||ai.length<3)fail('This role needs more reviewed problems.');squares=Array.from({length:25},(_,i)=>[3,12,20].includes(i)?ai.shift():core.shift());}
 return {id:uid(),no,set,role,squares:squares.slice(0,25).map(x=>({...x,claim:null})),kits:0};
}
export function chooseRole(s,token,role){
 const p=s.players.find(p=>p.token===token);if(!p)fail('Join the game first.',401);
 if(!getPersona(role))fail('Choose one of the listed roles.');
 p.role=role;
 if(s.variant==='personal'){
  const current=s.personalBoards[p.id];
  if(current.role!==role&&!current.squares.some(sq=>sq.claim))s.personalBoards[p.id]=board(current.no,current.set,role);
 }
 return p;
}
export function initial(variant='shared'){return {variant,personalBoards:{},ruleVersion:2,version:0,settings:{cooldown:0,picksPerRound:3,cap:3,kitLimit:null,firstFive:0,paused:false,ended:false,nextRoundAt:null,announcement:''},board:board(),history:[],players:[],claims:[],kits:[],notes:[],event:null};}
export function upgrade(s){
 s.notes ||= [];s.variant ||= 'shared';s.personalBoards ||= {};s.settings.nextRoundAt ||= null;s.settings.announcement ||= '';
 if((s.ruleVersion||1)<2){s.ruleVersion=2;s.settings.cooldown=0;s.settings.firstFive=0;s.settings.picksPerRound=3;}
 // Refresh displayed labels; claim audit records and earned prizes retain their original values.
 const latest=new Map(painCatalog.map(p=>[p.id,p]));
 for(let square of [s.board,...Object.values(s.personalBoards)].flatMap(b=>b.squares)){const copy=latest.get(square.id);if(copy&&(square.revision||1)<copy.revision)Object.assign(square,copy);}
 return s;
}
export function fail(message,status=400){throw Object.assign(new Error(message),{status});}
export function normalize(type,value){value=String(value||'').trim();if(type==='email'){if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value))fail('Enter a valid email address.');return value.toLowerCase();}if(type==='phone'){let p=value.replace(/[\s().-]/g,'');if(!/^\+\d{8,15}$/.test(p))fail('Include country code, for example +14155550123.');return p;}if(type==='linkedin'){try{let u=new URL(value.startsWith('http')?value:'https://'+value);if(!/^(www\.)?linkedin\.com$/.test(u.hostname)||!/^\/in\/[^/]+\/?$/.test(u.pathname))throw 0;return 'https://linkedin.com'+u.pathname.replace(/\/$/,'').toLowerCase();}catch{fail('Enter your LinkedIn profile URL (linkedin.com/in/…).');}}fail('Choose a contact method.');}
export function register(s,p,token){if(p.role!=null&&!getPersona(p.role))fail('Choose one of the listed roles.');let norm=normalize(p.type,p.contact);for(let k of ['name','company'])if(typeof p[k]!=='string'||!p[k].trim()||p[k].trim().length>80)fail('Enter a name and company, up to 80 characters each.');if(p.consent!==true)fail('Please accept the contact consent.');let existing=s.players.find(x=>x.norm===norm);if(existing){if(existing.token!==token)fail('This contact is already registered. Please use the original browser, or ask Jim for help.',409);return existing;}let player={id:uid(),token:uid(),role:p.role||null,name:p.name.trim(),company:p.company.trim(),type:p.type,contact:p.contact.trim(),norm,joined:Date.now(),consentAt:new Date().toISOString()};s.players.push(player);if(s.variant==='personal')s.personalBoards[player.id]=board(1,-1,player.role);return player;}
export function personal(s,token,now=Date.now()){let p=s.players.find(x=>x.token===token);if(!p)return null;let claims=s.claims.filter(x=>x.player===p.id&&!x.undone);let last=claims.at(-1);let current=s.variant==='personal'?(s.personalBoards[p.id]||s.board):s.board;let maxPicks=s.variant==='personal'?25:(s.settings.picksPerRound||3);let ownSquares=claims.filter(c=>c.board===current.id).map(c=>c.index);return {name:p.name,role:p.role||null,cardRole:current.role||null,rolePending:s.variant==='personal'&&!!p.role&&current.role!==p.role,notes:(s.notes||[]).filter(n=>n.player===p.id).map(({id,text,status})=>({id,text,status})),claims:claims.length,ownSquares,picksLeft:Math.max(0,maxPicks-ownSquares.length),maxPicks,readyAt:last?last.at+s.settings.cooldown*60000:0,kits:s.kits.filter(x=>x.player===p.id&&!x.revoked).map(({code,reason,handed,claim})=>({code,reason,handed,lines:s.claims.find(c=>c.id===claim)?.lines||[]})),unrated:claims.filter(x=>!x.rating).map(x=>({id:x.id,short:currentShort(x.pain)})),wins:claims.filter(c=>c.lines.length).map(c=>({id:c.id,lines:c.lines,boardNo:c.boardNo,outcome:c.outcome,kit:s.kits.find(k=>k.claim===c.id&&!k.revoked)?.code||null})),lastClaim:last?{id:last.id,lines:last.lines,outcome:last.outcome}:null};}
export function snapshot(s,token){let p=s.players.find(p=>p.token===token);let b=s.variant==='personal'&&p?s.personalBoards[p.id]:s.board;const counts=new Map();for(const c of s.claims.filter(c=>!c.undone)){let item=counts.get(c.pain.id)||{short:currentShort(c.pain),count:0};item.count++;counts.set(c.pain.id,item);}return {community:{players:s.players.length,marks:s.claims.filter(c=>!c.undone).length,popular:[...counts.values()].sort((a,b)=>b.count-a.count).slice(0,5)},variant:s.variant,version:s.version,settings:s.settings,recentWins:s.claims.filter(c=>!c.undone&&c.lines.length).slice(-4).reverse().map(c=>({id:c.id,lines:c.lines,boardNo:c.boardNo,at:c.at})),callouts:(s.notes||[]).filter(n=>n.status==='approved').slice(-6).map(({id,text})=>({id,text})),board:{id:b.id,no:b.no,squares:b.squares.map(x=>({id:x.id,short:x.short,full:x.full,topic:x.topic||'',claimed:!!x.claim})),count:b.squares.filter(x=>x.claim).length},lines:lines.map((l,i)=>({name:lineNames[i],count:l.filter(n=>b.squares[n].claim).length})),event:s.variant==='personal'?(p?b.event||null:null):s.event};}
export function claim(s,token,input,now=Date.now()){
 if(s.variant!=='personal')return applyClaim(s,token,input,now);
 const player=s.players.find(p=>p.token===token);if(!player)fail('Join the game first.',401);
 const shared=s.board,previousEvent=s.event;s.board=s.personalBoards[player.id];
 try{return applyClaim(s,token,input,now);}finally{s.board.event=s.event;s.personalBoards[player.id]=s.board;s.board=shared;s.event=previousEvent;}
}
function applyClaim(s,token,input,now=Date.now()){let p=s.players.find(x=>x.token===token);if(!p)fail('Join the game first.',401);let prior=s.claims.find(x=>x.request===input.request&&x.player===p.id);if(prior)return prior;if(typeof input.request!=='string'||input.request.length>80)fail('Invalid request.');if(s.settings.ended)fail('The game has ended.');if(s.settings.paused)fail('The game is paused. Try again shortly.');if(s.board.id!==input.board)fail('A new board has started. Pick a square on the new board.',409);if(!Number.isInteger(input.index)||input.index<0||input.index>24)fail('Choose a square.');let me=personal(s,token,now);if(me.picksLeft===0)fail('You have used your picks for this round. You get more when the next round starts.',429);if(me.readyAt>now)fail('Your next turn is not ready yet.',429);let sq=s.board.squares[input.index];if(sq.claim)fail('Just taken. Pick another square.',409);let before=lines.map(l=>l.every(n=>s.board.squares[n].claim));let c={id:uid(),request:input.request,player:p.id,at:now,board:s.board.id,boardNo:s.board.no,set:s.board.set,role:s.board.role||p.role||null,index:input.index,pain:{...sq},lines:[],outcome:'claimed',rating:null,undone:null};sq.claim=c.id;c.lines=lines.map((l,i)=>!before[i]&&l.every(n=>s.board.squares[n].claim)?lineNames[i]:null).filter(Boolean);let distinct=new Set(s.claims.filter(c=>!c.undone).map(c=>c.player));let reason=null;if(!distinct.has(p.id)&&distinct.size<s.settings.firstFive)reason='first_five';else if(c.lines.length&&(s.settings.kitLimit==null||s.kits.filter(k=>!k.revoked).length<s.settings.kitLimit)&&s.board.kits<s.settings.cap&&!s.kits.some(k=>k.player===p.id&&k.reason==='line_win'&&!k.revoked)){reason='line_win';s.board.kits++;}if(reason){let code;do{code=Array.from(crypto.getRandomValues(new Uint8Array(4)),v=>'23456789ABCDEFGHJKLMNPQRSTUVWXYZ'[v%31]).join('');}while(s.kits.some(k=>k.code===code));s.kits.push({id:uid(),player:p.id,claim:c.id,reason,code,handed:null,revoked:null});c.outcome=reason;}
s.claims.push(c);s.event={id:c.id,type:c.lines.length?'line':'claim',text:c.lines.length?c.lines.join(' + ')+' complete.':'Another problem shared.',at:now};if(s.board.squares.every(x=>x.claim)){s.history.push({...s.board,completedAt:now});s.board=board(s.board.no+1,s.board.set,s.variant==='personal'?p.role:null);s.event={...s.event,type:'reset',text:c.lines.length?c.lines.join(' + ')+' complete. Next round ready.':'Full board. Next round ready.'};}return c;}
export function addNote(s,token,input){
 const player=s.players.find(p=>p.token===token);if(!player)fail('Join the game first.',401);
 if(s.settings.ended)fail('The game has ended.');
 s.notes ||= [];
 const previous=s.notes.find(n=>n.player===player.id&&n.request===input.request);if(previous)return previous;
 if(typeof input.request!=='string'||input.request.length>80)fail('Invalid request.');
 const text=String(input.text||'').trim().replace(/\s+/g,' ');
 if(text.length<8||text.length>180)fail('Use 8 to 180 characters to describe the problem.');
 if(s.notes.filter(n=>n.player===player.id).length>=3)fail('You have shared three notes. Thanks for adding your perspective.');
 const note={id:uid(),request:input.request,player:player.id,text,status:'pending',at:Date.now()};s.notes.push(note);return note;
}
export function roundDue(s,now=Date.now()){return !s.settings.ended&&s.settings.nextRoundAt&&s.settings.nextRoundAt<=now;}
export function advanceRound(s,now=Date.now()){
 s.history.push({...s.board,skipped:true,completedAt:now});s.board=board(s.board.no+1,s.board.set);
 if(s.variant==='personal'){for(const id of Object.keys(s.personalBoards)){const old=s.personalBoards[id];s.history.push({...old,skipped:true,completedAt:now});s.personalBoards[id]=board(old.no+1,old.set,s.players.find(p=>p.id===id)?.role||null);}}
 s.settings.nextRoundAt=null;s.settings.announcement='';s.settings.paused=false;s.settings.ended=false;
 s.event={id:uid(),type:'reset',text:'The next round is ready. Your picks are back.',at:now};
 if(s.variant==='personal')for(const b of Object.values(s.personalBoards))b.event=s.event;
}
export function adminAction(s,p){if(p.action==='announce'){if(!Number.isFinite(p.startAt)||p.startAt<Date.now()+1000||p.startAt>Date.now()+7*86400000)fail('Choose a start time within the next seven days.');const message=String(p.message||'').trim();if(message.length>120)fail('Keep the announcement under 120 characters.');s.settings.nextRoundAt=p.startAt;s.settings.announcement=message||'Take a break. Another round is on its way.';s.settings.paused=true;s.settings.ended=false;return;}if(p.action==='cancel_announcement'){s.settings.nextRoundAt=null;s.settings.announcement='';return;}if(p.action==='moderate'){const n=(s.notes||[]).find(n=>n.id===p.id);if(!n)fail('Note not found.',404);if(!['approved','hidden'].includes(p.status))fail('Choose approve or hide.');n.status=p.status;return;}if(p.action==='settings'){if('kitLimit' in p){if(p.kitLimit!==null&&(!Number.isInteger(p.kitLimit)||p.kitLimit<0||p.kitLimit>5000))fail('Set kit stock from 0 to 5000, or leave it blank.');s.settings.kitLimit=p.kitLimit;}for(let [key,max] of [['picksPerRound',10],['cap',12]]){if(!Number.isInteger(p[key])||p[key]<(key==='picksPerRound'?1:0)||p[key]>max)fail('Settings are outside the allowed range.');s.settings[key]=p[key];}return;}if(p.action==='pause'){s.settings.paused=!s.settings.paused;if(!s.settings.paused){s.settings.nextRoundAt=null;s.settings.announcement='';}return;}if(p.action==='end'){s.settings.ended=true;s.settings.nextRoundAt=null;s.settings.announcement='';return;}if(p.action==='resume'){s.settings.ended=false;s.settings.paused=false;s.settings.nextRoundAt=null;s.settings.announcement='';return;}if(p.action==='skip'){advanceRound(s);return;}if(p.action==='hand'){let k=s.kits.find(k=>k.code===p.code&&!k.revoked);if(!k)fail('Kit not found.');k.handed=k.handed||Date.now();return;}if(p.action==='undo'){let c=s.claims.find(c=>c.id===p.id&&!c.undone);const target=s.variant==='personal'&&c?s.personalBoards[c.player]:s.board;if(!c||c.board!==target?.id)fail('Only claims on the current board can be undone.');if(s.kits.some(k=>k.claim===c.id&&k.handed&&!k.revoked))fail('This kit has already been handed over. The claim cannot be undone.');c.undone=Date.now();target.squares[c.index].claim=null;for(let k of s.kits.filter(k=>k.claim===c.id&&!k.revoked)){k.revoked=Date.now();if(k.reason==='line_win')target.kits--;}s.event={id:uid(),type:'undo',text:'A square has reopened.',at:Date.now()};return;}fail('Unknown action.');}
export function csv(s){const pt=t=>t?new Date(t).toLocaleString('en-US',{timeZone:'America/Los_Angeles'}):'';let rows=[['Timestamp (PT)','Board','Set','Square','Short pain','Full pain','Wedge','Persona','Name','Company','Contact type','Contact','Rating','Outcome','Lines','Kit code','Handed over','Handed time (PT)','Undone','Consent timestamp','Entry type','Display status','Selected role']];for(let c of s.claims){let p=s.players.find(p=>p.id===c.player),k=s.kits.find(k=>k.claim===c.id&&!k.revoked);rows.push([pt(c.at),c.boardNo,c.set<0?'Role card':c.set+1,'BINGO'[c.index%5]+(Math.floor(c.index/5)+1),c.pain.short,c.pain.full,c.pain.wedge,c.pain.persona,p.name,p.company,p.type,p.contact,c.rating||'',c.outcome,c.lines.join('; '),k?.code||'',k?.handed?'Y':'N',pt(k?.handed),c.undone?'Y':'N',p.consentAt,'square','',getPersona(c.role)?.label||'']);}for(const n of s.notes||[]){const p=s.players.find(p=>p.id===n.player);rows.push([pt(n.at),'','','','',n.text,'','',p.name,p.company,p.type,p.contact,'','written','','','','','',p.consentAt,'written note',n.status,getPersona(p.role)?.label||'']);}return '\uFEFF'+rows.map(row=>row.map(v=>'"'+String(v).replace(/^[=+@\-\t\r]/,"'$&").replaceAll('"','""')+'"').join(',')).join('\r\n');}
