"""
icc_pq -- build a Rec. ITU-R BT.2100 PQ ICC profile from scratch.

Why build one rather than ship one: PQ ICC profiles in the wild are vendor
assets (Apple ships one in /System/Library/ColorSync/Profiles/, Adobe ships
others). Copying one means embedding another vendor's copyright string into your
brand assets, and you cannot verify what is inside it. Generating the profile
means every byte is accounted for and the build is reproducible anywhere.

READ THIS BEFORE RELYING ON IT
------------------------------
A structurally valid PQ ICC profile is NOT the same thing as "this file renders
as HDR". The mechanisms browsers actually use to unlock headroom are:

  * CICP code points  -- AVIF / HEIF (nclx colr box), PNG (cICP chunk)
  * gain maps         -- JPEG (Ultra HDR / Adaptive HDR / ISO 21496-1)

ICC is a *colour management* mechanism. It describes a colour space; it does not
carry the "this is absolute luminance, give it headroom" signal that CICP does.
Apple's ecosystem does treat certain BT.2100 PQ profiles as HDR, but that
depends on the OS recognising the profile, which a self-built profile will not
reliably achieve.

So: this profile is worth shipping as an *experiment* (ICC survives re-encoding
far better than a gain map does, which makes it a reasonable bet on a pipeline
that transcodes), but a gain-map JPEG is the JPEG format with a proven path.
Do not present an ICC-PQ JPEG as guaranteed HDR.
"""

import struct
import numpy as np

import hdrkit as k

D50 = np.array([0.9642, 1.0000, 0.8249])
D65 = np.array([0.95047, 1.00000, 1.08883])

# ITU-R BT.2020 / BT.2100 primaries and white point
BT2020_PRIMARIES = {'r': (0.708, 0.292), 'g': (0.170, 0.797), 'b': (0.131, 0.046)}
BT2020_WHITE = (0.3127, 0.3290)

BRADFORD = np.array([
    [0.8951, 0.2664, -0.1614],
    [-0.7502, 1.7135, 0.0367],
    [0.0389, -0.0685, 1.0296],
])


# --------------------------------------------------------------------------
# Colour maths
# --------------------------------------------------------------------------

def _xy_to_XYZ(x, y, Y=1.0):
    return np.array([x * Y / y, Y, (1 - x - y) * Y / y])


def rgb_to_xyz_matrix(primaries, white_xy):
    """Standard derivation: scale each primary so the three sum to the white
    point, then the columns are the primaries' XYZ."""
    M = np.column_stack([_xy_to_XYZ(*primaries[c]) for c in ('r', 'g', 'b')])
    W = _xy_to_XYZ(*white_xy)
    s = np.linalg.solve(M, W)
    return M * s


def bradford_adaptation(src_white, dst_white):
    """Von Kries adaptation in Bradford cone space -- the transform ICC expects
    in the 'chad' tag."""
    s = BRADFORD @ src_white
    d = BRADFORD @ dst_white
    return np.linalg.inv(BRADFORD) @ np.diag(d / s) @ BRADFORD


# --------------------------------------------------------------------------
# ICC primitives
# --------------------------------------------------------------------------

def _s15f16(x):
    return struct.pack('>i', int(round(float(x) * 65536.0)))


def _xyz_type(xyz):
    return b'XYZ ' + b'\x00' * 4 + b''.join(_s15f16(v) for v in xyz)


def _curv_from_samples(samples):
    """curveType: a 1-D LUT of uint16 samples mapping device value -> linear.
    PQ cannot be written as an ICC parametricCurveType (those only cover simple
    gamma forms), so a sampled curve is the only faithful option."""
    n = len(samples)
    body = b'curv' + b'\x00' * 4 + struct.pack('>I', n)
    q = np.clip(np.round(np.asarray(samples) * 65535.0), 0, 65535).astype('>u2')
    return body + q.tobytes()


def _mluc(text):
    """multiLocalizedUnicodeType -- required for 'desc'/'cprt' in ICC v4."""
    utf16 = text.encode('utf-16-be')
    return (b'mluc' + b'\x00' * 4 + struct.pack('>I', 1) + struct.pack('>I', 12)
            + b'enUS' + struct.pack('>II', len(utf16), 28) + utf16)


def _sf32(matrix):
    flat = np.asarray(matrix).reshape(-1)
    return b'sf32' + b'\x00' * 4 + b''.join(_s15f16(v) for v in flat)


# --------------------------------------------------------------------------
# Profile assembly
# --------------------------------------------------------------------------

def pq_trc_samples(n=4096, peak_nits=k.PQ_MAX_NITS):
    """Device code -> linear light, normalised so `peak_nits` maps to 1.0.

    With peak_nits = 10000 this is true BT.2100 PQ: an ordinary white pixel
    (203 nits, per BT.2408) lands at 0.0203 relative. That is correct per the
    standard and is exactly why PQ needs a decoder that knows it is absolute --
    anything treating the value as relative renders the image very dark.
    """
    v = np.linspace(0.0, 1.0, n)
    return np.clip(k.pq_to_nits(v) / peak_nits, 0.0, 1.0)


def build_profile(description='Rec. ITU-R BT.2100 PQ',
                  copyright_text='Generated by hdr-logo-glow. No rights asserted.',
                  trc_samples=4096, peak_nits=k.PQ_MAX_NITS):
    """Return the bytes of an ICC v4.3 RGB display profile: BT.2020 primaries,
    PQ transfer curve, D50 PCS with a Bradford chromatic adaptation tag."""
    rgb2xyz_d65 = rgb_to_xyz_matrix(BT2020_PRIMARIES, BT2020_WHITE)
    chad = bradford_adaptation(D65, D50)
    rgb2xyz_d50 = chad @ rgb2xyz_d65

    trc = _curv_from_samples(pq_trc_samples(trc_samples, peak_nits))
    tags = [
        (b'desc', _mluc(description)),
        (b'cprt', _mluc(copyright_text)),
        (b'wtpt', _xyz_type(D50)),
        (b'chad', _sf32(chad)),
        (b'rXYZ', _xyz_type(rgb2xyz_d50[:, 0])),
        (b'gXYZ', _xyz_type(rgb2xyz_d50[:, 1])),
        (b'bXYZ', _xyz_type(rgb2xyz_d50[:, 2])),
        (b'rTRC', trc),
        (b'gTRC', trc),
        (b'bTRC', trc),
    ]

    # Identical TRC data is stored once and referenced three times -- the spec
    # explicitly allows shared tag elements, and it saves 24 KB.
    offsets, blobs, pos = {}, [], 128 + 4 + 12 * len(tags)
    table = []
    for sig, data in tags:
        key = data
        if key in offsets:
            off, size = offsets[key]
        else:
            off = pos
            size = len(data)
            pad = (-size) % 4
            blobs.append(data + b'\x00' * pad)
            pos += size + pad
            offsets[key] = (off, size)
        table.append((sig, off, size))

    total = pos
    header = bytearray(128)
    struct.pack_into('>I', header, 0, total)
    header[4:8] = b'    '                       # no preferred CMM
    struct.pack_into('>I', header, 8, 0x04300000)   # v4.3.0.0
    header[12:16] = b'mntr'                     # display device profile
    header[16:20] = b'RGB '
    header[20:24] = b'XYZ '
    struct.pack_into('>6H', header, 24, 2026, 1, 1, 0, 0, 0)
    header[36:40] = b'acsp'
    header[40:44] = b'\x00' * 4                 # platform: none
    struct.pack_into('>I', header, 44, 0)       # flags: not embedded, independent
    header[48:52] = b'\x00' * 4                 # device manufacturer
    header[52:56] = b'\x00' * 4                 # device model
    struct.pack_into('>Q', header, 56, 0)       # device attributes
    struct.pack_into('>I', header, 64, 0)       # rendering intent: perceptual
    header[68:80] = b''.join(_s15f16(v) for v in D50)
    header[80:84] = b'\x00' * 4                 # creator
    # bytes 84..99 profile ID (MD5) left zero; 100..127 reserved

    out = bytes(header) + struct.pack('>I', len(table))
    for sig, off, size in table:
        out += sig + struct.pack('>II', off, size)
    out += b''.join(blobs)
    assert len(out) == total, (len(out), total)
    return out


if __name__ == '__main__':
    import sys
    path = sys.argv[1] if len(sys.argv) > 1 else 'rec2100-pq.icc'
    data = build_profile()
    with open(path, 'wb') as f:
        f.write(data)
    print(f'wrote {path} ({len(data):,} bytes)')
